const PLACEHOLDER_SUPABASE_URL = 'https://placeholder.supabase.co'
const PLACEHOLDER_SUPABASE_ANON_KEY = 'anon-placeholder'
const PLACEHOLDER_SUPABASE_SERVICE_KEY = 'service-role-placeholder'
const PLACEHOLDER_RESEND_KEY = 're_test_placeholder'
const PLACEHOLDER_STRIPE_SECRET = 'sk_test_placeholder'
const PLACEHOLDER_STRIPE_WEBHOOK = 'whsec_placeholder'

process.env.NEXT_PUBLIC_SUPABASE_URL ||= PLACEHOLDER_SUPABASE_URL
process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ||= PLACEHOLDER_SUPABASE_ANON_KEY
process.env.SUPABASE_SERVICE_ROLE_KEY ||= PLACEHOLDER_SUPABASE_SERVICE_KEY
process.env.RESEND_API_KEY ||= PLACEHOLDER_RESEND_KEY
process.env.STRIPE_SECRET_KEY ||= PLACEHOLDER_STRIPE_SECRET
process.env.STRIPE_WEBHOOK_SECRET ||= PLACEHOLDER_STRIPE_WEBHOOK
