export type FeatureArea =
  | 'Core Care'
  | 'Progress & Content'
  | 'Payments & Plans'
  | 'Community & Growth'
  | 'Professional Tools'
  | 'Operations & Admin'
  | 'Trust & Safety';

export type FeatureAudience = 'Everyone' | 'Client' | 'Therapist' | 'Admin';
export type FeatureStatus = 'live' | 'beta';

export interface FeatureItem {
  id: string;
  title: string;
  description: string;
  href: string;
  area: FeatureArea;
  audience: FeatureAudience;
  status: FeatureStatus;
}

export const FEATURE_CATALOG: FeatureItem[] = [
  {
    id: 'dashboard',
    title: 'Dashboard',
    description: 'Main personal workspace and key actions.',
    href: '/dashboard',
    area: 'Core Care',
    audience: 'Client',
    status: 'live',
  },
  {
    id: 'book',
    title: 'Book Session',
    description: 'Primary booking flow for all session types.',
    href: '/book',
    area: 'Core Care',
    audience: 'Everyone',
    status: 'live',
  },
  {
    id: 'bookings',
    title: 'Bookings',
    description: 'Upcoming and historical sessions.',
    href: '/bookings',
    area: 'Core Care',
    audience: 'Client',
    status: 'live',
  },
  {
    id: 'journal',
    title: 'Journal',
    description: 'Personal check-ins and notes.',
    href: '/wellness',
    area: 'Progress & Content',
    audience: 'Client',
    status: 'live',
  },
  {
    id: 'resources',
    title: 'Materials Library',
    description: 'Guides, videos, and support content.',
    href: '/resources',
    area: 'Progress & Content',
    audience: 'Client',
    status: 'live',
  },
  {
    id: 'progress',
    title: 'Progress',
    description: 'Progress tracking and milestones.',
    href: '/progress',
    area: 'Progress & Content',
    audience: 'Client',
    status: 'live',
  },
  {
    id: 'progress-reports',
    title: 'Progress Reports',
    description: 'Longer-term progress reporting.',
    href: '/wellness?tab=progress',
    area: 'Progress & Content',
    audience: 'Client',
    status: 'live',
  },
  {
    id: 'insights',
    title: 'Insights',
    description: 'Data-driven wellness insights.',
    href: '/insights',
    area: 'Progress & Content',
    audience: 'Client',
    status: 'live',
  },
  {
    id: 'wallet',
    title: 'Wallet',
    description: 'Balance, transactions, and top-ups.',
    href: '/finances',
    area: 'Payments & Plans',
    audience: 'Client',
    status: 'live',
  },
  {
    id: 'subscriptions',
    title: 'Subscriptions',
    description: 'Manage active plans and tiers.',
    href: '/finances?tab=plans',
    area: 'Payments & Plans',
    audience: 'Client',
    status: 'live',
  },
  {
    id: 'plans',
    title: 'Plans',
    description: 'Browse and compare available plans.',
    href: '/finances?tab=plans',
    area: 'Payments & Plans',
    audience: 'Client',
    status: 'live',
  },
  {
    id: 'billing',
    title: 'Billing',
    description: 'Billing details and payment status.',
    href: '/finances?tab=billing',
    area: 'Payments & Plans',
    audience: 'Client',
    status: 'live',
  },
  {
    id: 'loyalty',
    title: 'Loyalty',
    description: 'Member benefits and rewards.',
    href: '/loyalty',
    area: 'Payments & Plans',
    audience: 'Client',
    status: 'live',
  },
  {
    id: 'community',
    title: 'Community',
    description: 'Community feed and engagement.',
    href: '/community',
    area: 'Community & Growth',
    audience: 'Everyone',
    status: 'live',
  },
  {
    id: 'notifications',
    title: 'Notifications',
    description: 'Alerts and communication center.',
    href: '/notifications',
    area: 'Community & Growth',
    audience: 'Everyone',
    status: 'live',
  },
  {
    id: 'referrals',
    title: 'Referrals',
    description: 'Invite flows and referral tracking.',
    href: '/referrals',
    area: 'Community & Growth',
    audience: 'Everyone',
    status: 'live',
  },
  {
    id: 'donations',
    title: 'Donations',
    description: 'Donation and support workflows.',
    href: '/donations',
    area: 'Community & Growth',
    audience: 'Everyone',
    status: 'live',
  },
  {
    id: 'therapist-dashboard',
    title: 'Therapist Dashboard',
    description: 'Therapist operational dashboard.',
    href: '/therapist/dashboard',
    area: 'Professional Tools',
    audience: 'Therapist',
    status: 'live',
  },
  {
    id: 'therapist-clients',
    title: 'Therapist Clients',
    description: 'Assigned client management.',
    href: '/therapist/clients',
    area: 'Professional Tools',
    audience: 'Therapist',
    status: 'live',
  },
  {
    id: 'therapist-session-notes',
    title: 'Session Notes',
    description: 'Clinical note-taking area.',
    href: '/therapist/session-notes',
    area: 'Professional Tools',
    audience: 'Therapist',
    status: 'live',
  },
  {
    id: 'therapist-templates',
    title: 'Therapist Templates',
    description: 'Reusable therapy templates.',
    href: '/therapist/templates',
    area: 'Professional Tools',
    audience: 'Therapist',
    status: 'live',
  },
  {
    id: 'availability',
    title: 'Availability',
    description: 'Manage therapist availability windows.',
    href: '/availability',
    area: 'Professional Tools',
    audience: 'Therapist',
    status: 'live',
  },
  {
    id: 'admin',
    title: 'Admin Panel',
    description: 'Core administration and moderation.',
    href: '/admin',
    area: 'Operations & Admin',
    audience: 'Admin',
    status: 'live',
  },
  {
    id: 'console-home',
    title: 'Console Home',
    description: 'Operations command center.',
    href: '/console',
    area: 'Operations & Admin',
    audience: 'Admin',
    status: 'live',
  },
  {
    id: 'console-users',
    title: 'Console Users',
    description: 'User management and controls.',
    href: '/console/users',
    area: 'Operations & Admin',
    audience: 'Admin',
    status: 'live',
  },
  {
    id: 'console-services',
    title: 'Console Services',
    description: 'Service catalog operations.',
    href: '/console/services',
    area: 'Operations & Admin',
    audience: 'Admin',
    status: 'live',
  },
  {
    id: 'console-payments',
    title: 'Console Payments',
    description: 'Payment operations and monitoring.',
    href: '/console/payments',
    area: 'Operations & Admin',
    audience: 'Admin',
    status: 'live',
  },
  {
    id: 'console-subscriptions',
    title: 'Console Subscriptions',
    description: 'Plan and subscription controls.',
    href: '/console/subscriptions',
    area: 'Operations & Admin',
    audience: 'Admin',
    status: 'live',
  },
  {
    id: 'console-analytics',
    title: 'Console Analytics',
    description: 'Operational analytics dashboard.',
    href: '/console/analytics',
    area: 'Operations & Admin',
    audience: 'Admin',
    status: 'live',
  },
  {
    id: 'console-cms',
    title: 'Console CMS',
    description: 'Content and publishing control.',
    href: '/console/cms',
    area: 'Operations & Admin',
    audience: 'Admin',
    status: 'live',
  },
  {
    id: 'console-community',
    title: 'Console Community',
    description: 'Community moderation tools.',
    href: '/console/community',
    area: 'Operations & Admin',
    audience: 'Admin',
    status: 'live',
  },
  {
    id: 'console-settings',
    title: 'Console Settings',
    description: 'System-level settings and config.',
    href: '/console/settings',
    area: 'Operations & Admin',
    audience: 'Admin',
    status: 'live',
  },
  {
    id: 'console-database',
    title: 'Console Database',
    description: 'Database diagnostics and tools.',
    href: '/console/database',
    area: 'Operations & Admin',
    audience: 'Admin',
    status: 'live',
  },
  {
    id: 'settings',
    title: 'Settings',
    description: 'Personal and app configuration.',
    href: '/settings',
    area: 'Trust & Safety',
    audience: 'Everyone',
    status: 'live',
  },
  {
    id: 'profile',
    title: 'Profile',
    description: 'Profile details and account data.',
    href: '/profile',
    area: 'Trust & Safety',
    audience: 'Everyone',
    status: 'live',
  },
  {
    id: 'personalization',
    title: 'Personalization',
    description: 'Personalization and preferences.',
    href: '/personalization',
    area: 'Trust & Safety',
    audience: 'Everyone',
    status: 'live',
  },
  {
    id: 'status',
    title: 'System Status',
    description: 'Platform and service status.',
    href: '/status',
    area: 'Trust & Safety',
    audience: 'Everyone',
    status: 'live',
  },
  {
    id: 'crisis',
    title: 'Crisis Support',
    description: 'Urgent support guidance and safe exits.',
    href: '/crisis',
    area: 'Trust & Safety',
    audience: 'Everyone',
    status: 'live',
  },
];

export const FEATURE_AREAS: FeatureArea[] = [
  'Core Care',
  'Progress & Content',
  'Payments & Plans',
  'Community & Growth',
  'Professional Tools',
  'Operations & Admin',
  'Trust & Safety',
];
