-- Add missing indexes for foreign keys
DO $$
BEGIN
  -- CREATE INDEX IF NOT EXISTS "idx_mfa_challenges_factor_id" ON "auth"."mfa_challenges" (factor_id);
  -- CREATE INDEX IF NOT EXISTS "idx_oauth_authorizations_client_id" ON "auth"."oauth_authorizations" (client_id);
  -- CREATE INDEX IF NOT EXISTS "idx_oauth_authorizations_user_id" ON "auth"."oauth_authorizations" (user_id);
  -- CREATE INDEX IF NOT EXISTS "idx_oauth_consents_user_id" ON "auth"."oauth_consents" (user_id);
  -- CREATE INDEX IF NOT EXISTS "idx_one_time_tokens_user_id" ON "auth"."one_time_tokens" (user_id);
  -- CREATE INDEX IF NOT EXISTS "idx_saml_relay_states_flow_state_id" ON "auth"."saml_relay_states" (flow_state_id);
  CREATE INDEX IF NOT EXISTS "idx_activity_logs_actor_id" ON "public"."activity_logs" (actor_id);
  CREATE INDEX IF NOT EXISTS "idx_admin_notes_author_id" ON "public"."admin_notes" (author_id);
  CREATE INDEX IF NOT EXISTS "idx_admin_notifications_created_by" ON "public"."admin_notifications" (created_by);
  CREATE INDEX IF NOT EXISTS "idx_agent_actions_user_id" ON "public"."agent_actions" (user_id);
  CREATE INDEX IF NOT EXISTS "idx_ai_conversations_user_id" ON "public"."ai_conversations" (user_id);
  CREATE INDEX IF NOT EXISTS "idx_ai_interactions_user_id" ON "public"."ai_interactions" (user_id);
  CREATE INDEX IF NOT EXISTS "idx_ai_messages_conversation_id" ON "public"."ai_messages" (conversation_id);
  CREATE INDEX IF NOT EXISTS "idx_audit_logs_user_id" ON "public"."audit_logs" (user_id);
  CREATE INDEX IF NOT EXISTS "idx_booking_booked_by_profile_id" ON "public"."booking" (booked_by_profile_id);
  CREATE INDEX IF NOT EXISTS "idx_booking_profile_id" ON "public"."booking" (profile_id);
  CREATE INDEX IF NOT EXISTS "idx_booking_service_variant_id" ON "public"."booking" (service_variant_id);
  CREATE INDEX IF NOT EXISTS "idx_booking_staff_id" ON "public"."booking" (staff_id);
  CREATE INDEX IF NOT EXISTS "idx_chat_messages_channel_id" ON "public"."chat_messages" (channel_id);
  CREATE INDEX IF NOT EXISTS "idx_chat_messages_sender_id" ON "public"."chat_messages" (sender_id);
  CREATE INDEX IF NOT EXISTS "idx_chat_participants_profile_id" ON "public"."chat_participants" (profile_id);
  CREATE INDEX IF NOT EXISTS "idx_comments_author_id" ON "public"."comments" (author_id);
  CREATE INDEX IF NOT EXISTS "idx_comments_parent_comment_id" ON "public"."comments" (parent_comment_id);
  CREATE INDEX IF NOT EXISTS "idx_comments_post_id" ON "public"."comments" (post_id);
  CREATE INDEX IF NOT EXISTS "idx_community_posts_edited_by" ON "public"."community_posts" (edited_by);
  CREATE INDEX IF NOT EXISTS "idx_community_posts_user_id" ON "public"."community_posts" (user_id);
  CREATE INDEX IF NOT EXISTS "idx_error_logs_user_id" ON "public"."error_logs" (user_id);
  CREATE INDEX IF NOT EXISTS "idx_memberships_profile_id" ON "public"."memberships" (profile_id);
  CREATE INDEX IF NOT EXISTS "idx_payment_proof_booking_id" ON "public"."payment_proof" (booking_id);
  CREATE INDEX IF NOT EXISTS "idx_payment_proof_user_id" ON "public"."payment_proof" (user_id);
  CREATE INDEX IF NOT EXISTS "idx_payment_proof_verified_by" ON "public"."payment_proof" (verified_by);
  CREATE INDEX IF NOT EXISTS "idx_payment_proof_wallet_transaction_id" ON "public"."payment_proof" (wallet_transaction_id);
  CREATE INDEX IF NOT EXISTS "idx_payments_user_id" ON "public"."payments" (user_id);
  CREATE INDEX IF NOT EXISTS "idx_posts_author_id" ON "public"."posts" (author_id);
  CREATE INDEX IF NOT EXISTS "idx_profiles_managed_by" ON "public"."profiles" (managed_by);
  CREATE INDEX IF NOT EXISTS "idx_relationships_from_profile_id" ON "public"."relationships" (from_profile_id);
  CREATE INDEX IF NOT EXISTS "idx_reviews_author_profile_id" ON "public"."reviews" (author_profile_id);
  CREATE INDEX IF NOT EXISTS "idx_reviews_booking_id" ON "public"."reviews" (booking_id);
  CREATE INDEX IF NOT EXISTS "idx_reviews_therapist_profile_id" ON "public"."reviews" (therapist_profile_id);
  CREATE INDEX IF NOT EXISTS "idx_role_permissions_role_id" ON "public"."role_permissions" (role_id);
  CREATE INDEX IF NOT EXISTS "idx_service_addon_service_id" ON "public"."service_addon" (service_id);
  CREATE INDEX IF NOT EXISTS "idx_service_translations_service_id" ON "public"."service_translations" (service_id);
  CREATE INDEX IF NOT EXISTS "idx_service_variant_service_id" ON "public"."service_variant" (service_id);
  CREATE INDEX IF NOT EXISTS "idx_staff_auth_user_id" ON "public"."staff" (auth_user_id);
  CREATE INDEX IF NOT EXISTS "idx_subscriptions_tier_id" ON "public"."subscriptions" (tier_id);
  CREATE INDEX IF NOT EXISTS "idx_sync_conflicts_resolved_by" ON "public"."sync_conflicts" (resolved_by);
  CREATE INDEX IF NOT EXISTS "idx_user_memory_user_id" ON "public"."user_memory" (user_id);
  CREATE INDEX IF NOT EXISTS "idx_user_notifications_user_id" ON "public"."user_notifications" (user_id);
  CREATE INDEX IF NOT EXISTS "idx_user_onboarding_answers_question_id" ON "public"."user_onboarding_answers" (question_id);
  CREATE INDEX IF NOT EXISTS "idx_user_role_assignments_assigned_by" ON "public"."user_role_assignments" (assigned_by);
  CREATE INDEX IF NOT EXISTS "idx_user_role_assignments_user_id" ON "public"."user_role_assignments" (user_id);
  CREATE INDEX IF NOT EXISTS "idx_wallet_transactions_wallet_id" ON "public"."wallet_transactions" (wallet_id);
  -- CREATE INDEX IF NOT EXISTS "idx_objects_bucket_id" ON "storage"."objects" (bucket_id);
  -- CREATE INDEX IF NOT EXISTS "idx_s3_multipart_uploads_bucket_id" ON "storage"."s3_multipart_uploads" (bucket_id);
  -- CREATE INDEX IF NOT EXISTS "idx_s3_multipart_uploads_parts_bucket_id" ON "storage"."s3_multipart_uploads_parts" (bucket_id);
  -- CREATE INDEX IF NOT EXISTS "idx_s3_multipart_uploads_parts_upload_id" ON "storage"."s3_multipart_uploads_parts" (upload_id);
  CREATE INDEX IF NOT EXISTS "idx__managed_webhooks_account_id" ON "stripe"."_managed_webhooks" (account_id);
  CREATE INDEX IF NOT EXISTS "idx_active_entitlements__account_id" ON "stripe"."active_entitlements" (_account_id);
  CREATE INDEX IF NOT EXISTS "idx_charges__account_id" ON "stripe"."charges" (_account_id);
  CREATE INDEX IF NOT EXISTS "idx_checkout_session_line_items__account_id" ON "stripe"."checkout_session_line_items" (_account_id);
  CREATE INDEX IF NOT EXISTS "idx_checkout_sessions__account_id" ON "stripe"."checkout_sessions" (_account_id);
  CREATE INDEX IF NOT EXISTS "idx_credit_notes__account_id" ON "stripe"."credit_notes" (_account_id);
  CREATE INDEX IF NOT EXISTS "idx_customers__account_id" ON "stripe"."customers" (_account_id);
  CREATE INDEX IF NOT EXISTS "idx_disputes__account_id" ON "stripe"."disputes" (_account_id);
  CREATE INDEX IF NOT EXISTS "idx_early_fraud_warnings__account_id" ON "stripe"."early_fraud_warnings" (_account_id);
  CREATE INDEX IF NOT EXISTS "idx_exchange_rates_from_usd__account_id" ON "stripe"."exchange_rates_from_usd" (_account_id);
  CREATE INDEX IF NOT EXISTS "idx_features__account_id" ON "stripe"."features" (_account_id);
  CREATE INDEX IF NOT EXISTS "idx_invoices__account_id" ON "stripe"."invoices" (_account_id);
  CREATE INDEX IF NOT EXISTS "idx_payment_intents__account_id" ON "stripe"."payment_intents" (_account_id);
  CREATE INDEX IF NOT EXISTS "idx_payment_methods__account_id" ON "stripe"."payment_methods" (_account_id);
  CREATE INDEX IF NOT EXISTS "idx_plans__account_id" ON "stripe"."plans" (_account_id);
  CREATE INDEX IF NOT EXISTS "idx_prices__account_id" ON "stripe"."prices" (_account_id);
  CREATE INDEX IF NOT EXISTS "idx_products__account_id" ON "stripe"."products" (_account_id);
  CREATE INDEX IF NOT EXISTS "idx_refunds__account_id" ON "stripe"."refunds" (_account_id);
  CREATE INDEX IF NOT EXISTS "idx_reviews__account_id" ON "stripe"."reviews" (_account_id);
  CREATE INDEX IF NOT EXISTS "idx_setup_intents__account_id" ON "stripe"."setup_intents" (_account_id);
  CREATE INDEX IF NOT EXISTS "idx_subscription_item_change_events_v2_beta__account_id" ON "stripe"."subscription_item_change_events_v2_beta" (_account_id);
  CREATE INDEX IF NOT EXISTS "idx_subscription_items__account_id" ON "stripe"."subscription_items" (_account_id);
  CREATE INDEX IF NOT EXISTS "idx_subscription_schedules__account_id" ON "stripe"."subscription_schedules" (_account_id);
  CREATE INDEX IF NOT EXISTS "idx_subscriptions__account_id" ON "stripe"."subscriptions" (_account_id);
  CREATE INDEX IF NOT EXISTS "idx_tax_ids__account_id" ON "stripe"."tax_ids" (_account_id);
END $$;